# Run tests and ensure program compiles, runs on non-main branches
kind: pipeline
type: docker
name: run tests node 12

steps:
  - name: install dependencies
    image: node:12
    pull: if-not-exists
    commands:
      - npm ci
  - name: run build
    image: node:12
    commands:
      - npm run build
  - name: test
    image: node:12
    pull: if-not-exists
    commands:
      - npm run test

trigger:
  event:
    - push # trigger pipeline on push to any branch

---
# Run tests and ensure program compiles, runs on non-main branches
kind: pipeline
type: docker
name: run tests node 10

steps:
  - name: install dependencies
    image: node:10
    pull: if-not-exists
    commands:
      - npm ci
  - name: run build
    image: node:10
    commands:
      - npm run build
  - name: test
    image: node:10
    pull: if-not-exists
    commands:
      - npm run test

trigger:
  event:
    - push # trigger pipeline on push to any branch

---
kind: pipeline
type: docker
name: tag

steps:
  - name: install dependencies
    image: node:12
    pull: if-not-exists
    commands:
      - npm ci
  - name: run build
    image: node:12
    commands:
      - npm run build
  - name: push docker
    image: plugins/docker
    settings:
      repo: nytimes/library
      tags:
        - latest
        - ${DRONE_TAG}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # cache_from:
        # - nytimes/library:latest
        # we are not cacheing right now because we are rate limited
trigger:
  event:
    - tag # trigger pipeline on tag release
