name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: nytimes/library

      - name: Build and push Docker image
        uses: docker/build-push-action@4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }} # just to be safe
          tags: ${{ steps.meta.outputs.tags }} # automatically tags with latest, version from tag
          labels: ${{ steps.meta.outputs.labels }}
